CREATE DATABASE IF NOT EXISTS ca_attendance
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE ca_attendance;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_no VARCHAR(32) NOT NULL COMMENT '学号或账号，系统唯一身份标识',
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希，后端使用 BCrypt',
  role VARCHAR(20) NOT NULL DEFAULT 'MEMBER' COMMENT 'MEMBER, MINISTER, PRESIDENT, ADMIN',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, DISABLED',
  grade VARCHAR(20) NULL COMMENT '年级，例如 2023级',
  must_change_password TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否强制首次登录后修改密码',
  last_login_at DATETIME NULL COMMENT '最后登录时间',
  disabled_at DATETIME NULL COMMENT '停用时间',
  disabled_by BIGINT UNSIGNED NULL COMMENT '停用操作人',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_student_no (student_no),
  KEY idx_users_role_status (role, status),
  KEY idx_users_name (name),
  KEY idx_users_disabled_by (disabled_by),
  KEY idx_users_created_by (created_by),
  KEY idx_users_updated_by (updated_by),
  CONSTRAINT fk_users_disabled_by FOREIGN KEY (disabled_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_users_role CHECK (role IN ('MEMBER', 'MINISTER', 'PRESIDENT', 'ADMIN')),
  CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS duty_weekday_settings (
  weekday TINYINT UNSIGNED NOT NULL COMMENT '星期：1=周一，2=周二，...，7=周日',
  weekday_name VARCHAR(16) NOT NULL COMMENT '星期名称',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否为值班日',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (weekday),
  KEY idx_duty_weekday_enabled (enabled),
  KEY idx_duty_weekday_updated_by (updated_by),
  CONSTRAINT fk_duty_weekday_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_duty_weekday_range CHECK (weekday BETWEEN 1 AND 7)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班星期配置表';

CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户 ID',
  student_no_snapshot VARCHAR(32) NOT NULL COMMENT '提交时的学号快照',
  name_snapshot VARCHAR(64) NOT NULL COMMENT '提交时的姓名快照',
  duty_date DATE NOT NULL COMMENT '值班日期，按签到时间取日期',
  duty_weekday TINYINT UNSIGNED NOT NULL COMMENT '签到发生时对应星期：1=周一，...，7=周日',
  is_duty_day TINYINT(1) NOT NULL DEFAULT 1 COMMENT '提交当天按配置是否为值班日',
  check_in_time DATETIME NOT NULL COMMENT '签到时间',
  check_out_time DATETIME NULL COMMENT '签退时间',
  check_in_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'NOT_SUBMITTED, PENDING, APPROVED, REJECTED, AUTO_APPROVED',
  check_out_status VARCHAR(20) NOT NULL DEFAULT 'NOT_SUBMITTED' COMMENT 'NOT_SUBMITTED, PENDING, APPROVED, REJECTED, AUTO_APPROVED',
  check_in_reviewed_by BIGINT UNSIGNED NULL COMMENT '签到审核人',
  check_out_reviewed_by BIGINT UNSIGNED NULL COMMENT '签退审核人',
  check_in_reviewed_at DATETIME NULL COMMENT '签到审核时间',
  check_out_reviewed_at DATETIME NULL COMMENT '签退审核时间',
  check_in_reject_reason VARCHAR(500) NULL COMMENT '签到驳回原因',
  check_out_reject_reason VARCHAR(500) NULL COMMENT '签退驳回原因',
  duration_minutes INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '原始时长分钟数，签退时间减签到时间',
  valid_hours INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '有效时长，按小时四舍五入取整数',
  effective_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, VALID, INVALID, INCOMPLETE',
  source VARCHAR(20) NOT NULL DEFAULT 'PUBLIC' COMMENT 'PUBLIC, ADMIN_MANUAL',
  manual_reason VARCHAR(500) NULL COMMENT '后台手动补改原因',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人，公开页提交时可为空',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_attendance_user_date (user_id, duty_date),
  KEY idx_attendance_duty_date (duty_date),
  KEY idx_attendance_student_no_date (student_no_snapshot, duty_date),
  KEY idx_attendance_status (check_in_status, check_out_status, effective_status),
  KEY idx_attendance_open_record (user_id, check_out_time),
  KEY idx_attendance_check_in_reviewed_by (check_in_reviewed_by),
  KEY idx_attendance_check_out_reviewed_by (check_out_reviewed_by),
  KEY idx_attendance_created_by (created_by),
  KEY idx_attendance_updated_by (updated_by),
  CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_check_in_reviewed_by FOREIGN KEY (check_in_reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_check_out_reviewed_by FOREIGN KEY (check_out_reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_attendance_weekday_range CHECK (duty_weekday BETWEEN 1 AND 7),
  CONSTRAINT chk_attendance_check_in_status CHECK (check_in_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED')),
  CONSTRAINT chk_attendance_check_out_status CHECK (check_out_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED')),
  CONSTRAINT chk_attendance_effective_status CHECK (effective_status IN ('PENDING', 'VALID', 'INVALID', 'INCOMPLETE')),
  CONSTRAINT chk_attendance_source CHECK (source IN ('PUBLIC', 'ADMIN_MANUAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班签到签退记录表';

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  operator_user_id BIGINT UNSIGNED NULL COMMENT '操作人 ID',
  operator_student_no VARCHAR(32) NULL COMMENT '操作人学号快照',
  operator_name VARCHAR(64) NULL COMMENT '操作人姓名快照',
  action_type VARCHAR(50) NOT NULL COMMENT '操作类型',
  target_type VARCHAR(50) NOT NULL COMMENT '操作对象类型',
  target_id BIGINT UNSIGNED NULL COMMENT '操作对象 ID',
  before_data JSON NULL COMMENT '修改前数据',
  after_data JSON NULL COMMENT '修改后数据',
  reason VARCHAR(500) NULL COMMENT '操作原因',
  ip_address VARCHAR(64) NULL COMMENT 'IP 地址',
  user_agent VARCHAR(500) NULL COMMENT '浏览器 User-Agent',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_operation_logs_operator (operator_user_id),
  KEY idx_operation_logs_action_type (action_type),
  KEY idx_operation_logs_target (target_type, target_id),
  KEY idx_operation_logs_created_at (created_at),
  CONSTRAINT fk_operation_logs_operator FOREIGN KEY (operator_user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) NOT NULL COMMENT '配置键',
  setting_value VARCHAR(1000) NOT NULL COMMENT '配置值',
  description VARCHAR(255) NULL COMMENT '配置说明',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (setting_key),
  KEY idx_app_settings_updated_by (updated_by),
  CONSTRAINT fk_app_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统配置表';
