CREATE DATABASE IF NOT EXISTS ca_attendance
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE ca_attendance;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_no VARCHAR(32) NOT NULL COMMENT '学号或账号，系统唯一身份标识',
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希，后端使用 BCrypt',
  role VARCHAR(20) NOT NULL DEFAULT 'MEMBER' COMMENT 'MEMBER, MINISTER, PRESIDENT, ADMIN',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, DISABLED',
  phone VARCHAR(20) NULL COMMENT '手机号',
  major VARCHAR(100) NULL COMMENT '学院',
  grade VARCHAR(20) NULL COMMENT '年级，例如 2023级',
  qq VARCHAR(32) NULL COMMENT 'QQ',
  must_change_password TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否强制首次登录后修改密码',
  last_login_at DATETIME NULL COMMENT '最后登录时间',
  disabled_at DATETIME NULL COMMENT '停用时间',
  disabled_by BIGINT UNSIGNED NULL COMMENT '停用操作人',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_student_no (student_no),
  KEY idx_users_role_status (role, status),
  KEY idx_users_name (name),
  KEY idx_users_disabled_by (disabled_by),
  KEY idx_users_created_by (created_by),
  KEY idx_users_updated_by (updated_by),
  CONSTRAINT fk_users_disabled_by FOREIGN KEY (disabled_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_users_role CHECK (role IN ('MEMBER', 'MINISTER', 'PRESIDENT', 'ADMIN')),
  CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS duty_weekday_settings (
  weekday TINYINT UNSIGNED NOT NULL COMMENT '星期：1=周一，2=周二，...，7=周日',
  weekday_name VARCHAR(16) NOT NULL COMMENT '星期名称',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否为值班日',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (weekday),
  KEY idx_duty_weekday_enabled (enabled),
  KEY idx_duty_weekday_updated_by (updated_by),
  CONSTRAINT fk_duty_weekday_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_duty_weekday_range CHECK (weekday BETWEEN 1 AND 7)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班星期配置表';

CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户 ID',
  student_no_snapshot VARCHAR(32) NOT NULL COMMENT '提交时的学号快照',
  name_snapshot VARCHAR(64) NOT NULL COMMENT '提交时的姓名快照',
  duty_date DATE NOT NULL COMMENT '值班日期，按签到时间取日期',
  duty_weekday TINYINT UNSIGNED NOT NULL COMMENT '签到发生时对应星期：1=周一，...，7=周日',
  is_duty_day TINYINT(1) NOT NULL DEFAULT 1 COMMENT '提交当天按配置是否为值班日',
  check_in_time DATETIME NOT NULL COMMENT '签到时间',
  check_out_time DATETIME NULL COMMENT '签退时间',
  check_in_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'NOT_SUBMITTED, PENDING, APPROVED, REJECTED, AUTO_APPROVED',
  check_out_status VARCHAR(20) NOT NULL DEFAULT 'NOT_SUBMITTED' COMMENT 'NOT_SUBMITTED, PENDING, APPROVED, REJECTED, AUTO_APPROVED',
  check_in_reviewed_by BIGINT UNSIGNED NULL COMMENT '签到审核人',
  check_out_reviewed_by BIGINT UNSIGNED NULL COMMENT '签退审核人',
  check_in_reviewed_at DATETIME NULL COMMENT '签到审核时间',
  check_out_reviewed_at DATETIME NULL COMMENT '签退审核时间',
  check_in_reject_reason VARCHAR(500) NULL COMMENT '签到驳回原因',
  check_out_reject_reason VARCHAR(500) NULL COMMENT '签退驳回原因',
  duration_minutes INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '原始时长分钟数，签退时间减签到时间',
  valid_hours INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '有效时长，按小时四舍五入取整数',
  effective_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, VALID, INVALID, INCOMPLETE',
  source VARCHAR(20) NOT NULL DEFAULT 'PUBLIC' COMMENT 'PUBLIC, ADMIN_MANUAL',
  manual_reason VARCHAR(500) NULL COMMENT '后台手动补改原因',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人，公开页提交时可为空',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_attendance_user_date (user_id, duty_date),
  KEY idx_attendance_duty_date (duty_date),
  KEY idx_attendance_student_no_date (student_no_snapshot, duty_date),
  KEY idx_attendance_status (check_in_status, check_out_status, effective_status),
  KEY idx_attendance_open_record (user_id, check_out_time),
  KEY idx_attendance_check_in_reviewed_by (check_in_reviewed_by),
  KEY idx_attendance_check_out_reviewed_by (check_out_reviewed_by),
  KEY idx_attendance_created_by (created_by),
  KEY idx_attendance_updated_by (updated_by),
  CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_check_in_reviewed_by FOREIGN KEY (check_in_reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_check_out_reviewed_by FOREIGN KEY (check_out_reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_attendance_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_attendance_weekday_range CHECK (duty_weekday BETWEEN 1 AND 7),
  CONSTRAINT chk_attendance_check_in_status CHECK (check_in_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED')),
  CONSTRAINT chk_attendance_check_out_status CHECK (check_out_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED')),
  CONSTRAINT chk_attendance_effective_status CHECK (effective_status IN ('PENDING', 'VALID', 'INVALID', 'INCOMPLETE')),
  CONSTRAINT chk_attendance_source CHECK (source IN ('PUBLIC', 'ADMIN_MANUAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班签到签退记录表';

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  operator_user_id BIGINT UNSIGNED NULL COMMENT '操作人 ID',
  operator_student_no VARCHAR(32) NULL COMMENT '操作人学号快照',
  operator_name VARCHAR(64) NULL COMMENT '操作人姓名快照',
  action_type VARCHAR(50) NOT NULL COMMENT '操作类型',
  target_type VARCHAR(50) NOT NULL COMMENT '操作对象类型',
  target_id BIGINT UNSIGNED NULL COMMENT '操作对象 ID',
  before_data JSON NULL COMMENT '修改前数据',
  after_data JSON NULL COMMENT '修改后数据',
  reason VARCHAR(500) NULL COMMENT '操作原因',
  ip_address VARCHAR(64) NULL COMMENT 'IP 地址',
  user_agent VARCHAR(500) NULL COMMENT '浏览器 User-Agent',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_operation_logs_operator (operator_user_id),
  KEY idx_operation_logs_action_type (action_type),
  KEY idx_operation_logs_target (target_type, target_id),
  KEY idx_operation_logs_created_at (created_at),
  CONSTRAINT fk_operation_logs_operator FOREIGN KEY (operator_user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) NOT NULL COMMENT '配置键',
  setting_value VARCHAR(1000) NOT NULL COMMENT '配置值',
  description VARCHAR(255) NULL COMMENT '配置说明',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (setting_key),
  KEY idx_app_settings_updated_by (updated_by),
  CONSTRAINT fk_app_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统配置表';

CREATE TABLE IF NOT EXISTS training_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '培训标题',
  training_date DATE NOT NULL COMMENT '培训日期',
  start_time TIME NULL COMMENT '开始时间',
  end_time TIME NULL COMMENT '结束时间',
  location VARCHAR(120) NULL COMMENT '培训地点',
  speaker VARCHAR(120) NULL COMMENT '主讲人',
  description VARCHAR(500) NULL COMMENT '培训说明',
  status VARCHAR(20) NOT NULL DEFAULT 'PLANNED' COMMENT 'PLANNED, COMPLETED, CANCELED, ARCHIVED',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_training_sessions_date_status (training_date, status),
  KEY idx_training_sessions_created_by (created_by),
  KEY idx_training_sessions_updated_by (updated_by),
  CONSTRAINT fk_training_sessions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_training_sessions_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_training_sessions_status CHECK (status IN ('PLANNED', 'COMPLETED', 'CANCELED', 'ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='培训场次表';

CREATE TABLE IF NOT EXISTS training_participants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_id BIGINT UNSIGNED NOT NULL COMMENT '培训场次 ID',
  user_id BIGINT UNSIGNED NULL COMMENT '关联成员 ID，外部人员可为空',
  student_no_snapshot VARCHAR(32) NOT NULL COMMENT '学号快照',
  name_snapshot VARCHAR(64) NOT NULL COMMENT '姓名快照',
  attendance_status VARCHAR(20) NOT NULL DEFAULT 'PRESENT' COMMENT 'PRESENT, ABSENT, LEAVE',
  remark VARCHAR(500) NULL COMMENT '备注',
  source VARCHAR(20) NOT NULL DEFAULT 'MANUAL' COMMENT 'MANUAL, IMPORT',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_training_participants_session_student (session_id, student_no_snapshot),
  KEY idx_training_participants_user (user_id),
  KEY idx_training_participants_status (attendance_status),
  KEY idx_training_participants_created_by (created_by),
  KEY idx_training_participants_updated_by (updated_by),
  CONSTRAINT fk_training_participants_session FOREIGN KEY (session_id) REFERENCES training_sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_training_participants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_training_participants_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_training_participants_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_training_participants_status CHECK (attendance_status IN ('PRESENT', 'ABSENT', 'LEAVE')),
  CONSTRAINT chk_training_participants_source CHECK (source IN ('MANUAL', 'IMPORT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='培训参与记录表';

CREATE TABLE IF NOT EXISTS duty_schedule_slots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  weekday TINYINT UNSIGNED NOT NULL COMMENT '星期：1=周一，2=周二，...，7=周日',
  start_time TIME NULL COMMENT '开始时间',
  end_time TIME NULL COMMENT '结束时间',
  title VARCHAR(100) NOT NULL DEFAULT '值班' COMMENT '排班标题',
  location VARCHAR(120) NULL COMMENT '值班地点',
  note VARCHAR(500) NULL COMMENT '备注',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, ARCHIVED',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_duty_schedule_weekday_enabled (weekday, enabled, status),
  KEY idx_duty_schedule_created_by (created_by),
  KEY idx_duty_schedule_updated_by (updated_by),
  CONSTRAINT fk_duty_schedule_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_duty_schedule_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_duty_schedule_weekday CHECK (weekday BETWEEN 1 AND 7),
  CONSTRAINT chk_duty_schedule_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班周排班时间段表';

CREATE TABLE IF NOT EXISTS duty_schedule_assignees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slot_id BIGINT UNSIGNED NOT NULL COMMENT '排班时间段 ID',
  user_id BIGINT UNSIGNED NULL COMMENT '关联成员 ID，手动填写外部姓名时可为空',
  student_no_snapshot VARCHAR(32) NULL COMMENT '学号快照',
  name_snapshot VARCHAR(64) NOT NULL COMMENT '姓名快照',
  sort_order INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '显示顺序',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_duty_schedule_assignee_slot (slot_id, sort_order),
  KEY idx_duty_schedule_assignee_user (user_id),
  CONSTRAINT fk_duty_schedule_assignee_slot FOREIGN KEY (slot_id) REFERENCES duty_schedule_slots (id) ON DELETE CASCADE,
  CONSTRAINT fk_duty_schedule_assignee_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='值班周排班人员表';

CREATE TABLE IF NOT EXISTS repair_cases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  case_no VARCHAR(32) NOT NULL COMMENT '维修事务编号',
  agreement_type VARCHAR(30) NOT NULL DEFAULT 'PERSONAL_DEVICE' COMMENT 'PERSONAL_DEVICE, PUBLIC_DEVICE',
  owner_name VARCHAR(64) NOT NULL COMMENT '送修人姓名',
  owner_phone VARCHAR(40) NULL COMMENT '送修人联系方式',
  owner_org VARCHAR(120) NULL COMMENT '学院、部门或单位',
  device_type VARCHAR(80) NOT NULL COMMENT '设备类型',
  device_brand VARCHAR(80) NULL COMMENT '品牌',
  device_model VARCHAR(120) NULL COMMENT '型号',
  device_serial VARCHAR(120) NULL COMMENT '序列号或资产编号',
  accessories VARCHAR(500) NULL COMMENT '随附物品',
  fault_description VARCHAR(1000) NOT NULL COMMENT '故障描述',
  service_description VARCHAR(1000) NULL COMMENT '处理记录',
  data_backup_confirmed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已提醒数据备份',
  risk_acknowledged TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否确认维修风险',
  privacy_acknowledged TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否确认隐私提示',
  status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED' COMMENT 'RECEIVED, DIAGNOSING, REPAIRING, WAITING_PICKUP, COMPLETED, CANCELED',
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '接收时间',
  completed_at DATETIME NULL COMMENT '完成时间',
  handler_user_id BIGINT UNSIGNED NULL COMMENT '处理人',
  handler_name_snapshot VARCHAR(64) NULL COMMENT '处理人姓名快照',
  remark VARCHAR(1000) NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  updated_by BIGINT UNSIGNED NULL COMMENT '最后修改人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_repair_cases_case_no (case_no),
  KEY idx_repair_cases_status_received (status, received_at),
  KEY idx_repair_cases_owner (owner_name, owner_phone),
  KEY idx_repair_cases_handler (handler_user_id),
  KEY idx_repair_cases_created_by (created_by),
  KEY idx_repair_cases_updated_by (updated_by),
  CONSTRAINT fk_repair_cases_handler FOREIGN KEY (handler_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_repair_cases_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_repair_cases_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_repair_cases_agreement_type CHECK (agreement_type IN ('PERSONAL_DEVICE', 'PUBLIC_DEVICE')),
  CONSTRAINT chk_repair_cases_status CHECK (status IN ('RECEIVED', 'DIAGNOSING', 'REPAIRING', 'WAITING_PICKUP', 'COMPLETED', 'CANCELED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='协会维修事务记录表';
