import { createApp } from "vue";
import App from "./App.vue";
import { router } from "./app/router";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/service-status.css";
import "./styles/components.css";
import "./styles/layouts.css";
import "./styles/kiosk.css";
import "./styles/admin-shell.css";
import "./styles/admin-polish.css";
import "./styles/today.css";
import "./styles/schedule.css";
import "./styles/admin-details.css";
import "./styles/premium-kiosk.css";
import "./styles/premium-admin.css";
import "./styles/signal-admin.css";
import "./styles/signal-kiosk.css";
import "./styles/signal-auth.css";

createApp(App).use(router).mount("#app");
