import { expect,test,type Page } from '@playwright/test';
async function install(page:Page,appearance:string){
 const fields=[{id:'studentNo',label:'学号',defaultSelected:true},{id:'name',label:'姓名',defaultSelected:true},{id:'college',label:'学院',defaultSelected:true}];const writes:any[]=[];let fail=true;let items=[1,2].map(id=>({id,caseNo:'WX-DEMO-00'+id,deviceBrand:'示例设备',deviceModel:'A'+id,deviceType:'笔记本电脑',deletedAt:'2026-09-12T10:30:00',deletedByName:'示例管理员'}));
 await page.addInitScript(()=>localStorage.setItem('ca_attendance_token','data-finish-fictional-token'));
 await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;const json=(body:any,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 if(req.method()!=='GET'){const body=req.postData()?req.postDataJSON():null;writes.push({path,body});
 if(path==='/api/exports/preview')return json({source:'members',sourceLabel:'成员名册',fields:fields.filter(f=>body.fields.includes(f.id)),rows:[{studentNo:'20260001',name:'示例成员甲',college:'计算机学院'}],totalRows:1,truncated:false});
 if(path==='/api/exports/excel')return route.fulfill({status:200,contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',body:'FICTIONAL DOWNLOAD PAYLOAD'});
 if(path.endsWith('/restore')){if(fail){fail=false;return json({message:'模拟恢复失败，请重试'},500)}items=items.filter(i=>i.id!==1);return json({})}
 if(path.endsWith('/purge')){items=items.filter(i=>i.id!==2);return json({})}return json({});}
 if(path==='/api/public/appearance')return json({appearance,version:1});if(path==='/api/access/context')return json({mode:'LOCAL',kioskAvailable:true,allowedRemoteRoles:[]});if(path==='/api/setup/status')return json({initialized:true});if(path==='/api/auth/me')return json({id:9,name:'示例管理员',studentNo:'demo-admin',role:'ADMIN',mustChangePassword:false});
 if(path==='/api/exports/options')return json({sources:[{id:'members',label:'成员名册',fields,filters:[]}]});if(path==='/api/maintenance/summary')return json({datasets:[{key:'users',label:'成员名册',total:1,detail:'1 名成员'}],backups:{count:0,totalSize:0}});if(path==='/api/repairs/recycle-bin')return json(items);return json([]);
 });return writes;
}
for(const appearance of ['CLASSIC','EDITORIAL','SPATIAL']){
 test(`${appearance} export selection invalidates preview and keeps download payload`,async({page})=>{
 const writes=await install(page,appearance);await page.setViewportSize({width:1440,height:960});await page.goto('/#/admin/data?tab=export');await page.getByRole('button',{name:'调整条件'}).click();await expect(page.locator('#data-export-config')).toBeVisible();await page.locator('[name=export-field-college]').uncheck();await page.locator('#data-export-config').getByRole('button',{name:'生成预览'}).click();await expect(page.locator('.data-preview-table')).toContainText('示例成员甲');expect(writes[0].body.fields).toEqual(['studentNo','name']);
 await page.locator('[name=export-field-college]').check();await expect(page.getByRole('button',{name:'导出 Excel'})).toBeDisabled();await page.locator('#data-export-config').getByRole('button',{name:'生成预览'}).click();await expect(page.getByRole('button',{name:'导出 Excel'})).toBeEnabled();await page.locator('[name=export-filename]').fill('示例导出');const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 Excel'}).click();await download;expect(writes.find(w=>w.path==='/api/exports/excel').body.filename).toBe('示例导出');
 await page.setViewportSize({width:390,height:844});await expect(page.locator('#data-export-config')).toHaveAttribute('role','dialog');await page.keyboard.press('Escape');await expect(page.locator('#data-export-config')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
 });
 test(`${appearance} recycle retries restore and requires identifier for permanent deletion`,async({page})=>{
 const writes=await install(page,appearance);await page.goto('/#/admin/data?tab=recycle');await page.getByRole('button',{name:'恢复维修事务：WX-DEMO-001'}).click();await expect(page.getByText('模拟恢复失败，请重试',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'恢复维修事务：WX-DEMO-001'})).toBeEnabled();await page.getByRole('button',{name:'恢复维修事务：WX-DEMO-001'}).click();await expect(page.getByRole('button',{name:'恢复维修事务：WX-DEMO-001'})).toHaveCount(0);
 await page.getByRole('button',{name:'彻底删除维修事务：WX-DEMO-002'}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'取消',exact:true}).click();expect(writes.filter(w=>w.path.endsWith('/purge'))).toHaveLength(0);await page.getByRole('button',{name:'彻底删除维修事务：WX-DEMO-002'}).click();await dialog.locator('textarea').fill('wrong');await dialog.getByRole('button',{name:'彻底删除',exact:true}).click();expect(writes.filter(w=>w.path.endsWith('/purge'))).toHaveLength(0);await dialog.locator('textarea').fill('WX-DEMO-002');await dialog.getByRole('button',{name:'彻底删除',exact:true}).click();await expect(page.getByText('回收站为空',{exact:true})).toBeVisible();expect(writes.filter(w=>w.path.endsWith('/purge'))).toHaveLength(1);
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:960,height:720});await page.evaluate(()=>document.body.style.zoom='1.5');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
 });
}
